#!/bin/sh

HEADER='\033[95m'
BLUE='\033[94m'
CYAN='\033[96m'
GREEN='\033[92m'
RED1='\033[93m'
RED2='\033[91m'
WHITE='\033[0m'
UNDERLINE='\033[4m'

ver1="33"
ver="$ver1 ~ C & C++ have been separated && update bug fix"
upd=0
cu="\n${HEADER}Commands usage:\n\ncarrot -cpp <path>\nExecute C++ program\n\ncarrot -c <path>\nExecute C program\n\ncarrot -repeat <string>\nRepeats the string you wrote\n\ncarrot -carrotedit\nOpens the Carrotshell program for you to edit\n\ncarrot -remove <file path>\nRemoves specified file\n\ncarrot -pi <package>\nInstalls the specified package\n\ncarrot -pr <package>\nRemoves the specified package\n\ncarrot -pu <package>\nUpdates apt and upgrades all packages\n\ncarrot -deb [-i/-r] <path>\nInstalls[-i]/Removes[-r] .deb package\n\ncarrot -update\nUpdates Carrotshell\n\ncarrot -rustdir <path>\nSets Rust Cargo directory (usually ~/.cargo/bin)\n\ncarrot -rust <path>\nExecute Rust program\n\n${GREEN}Carrotshell V${ver}$WHITE\n"

if [ ! -f ~/.Carrotshell/ini ]; then
    echo "\nInitialization..."
    if [ ! -d ~/.Carrotshell ]; then
        mkdir ~/.Carrotshell
    fi
    echo "Delete this file to re-inizialize Carrotshell!" >> ~/.Carrotshell/ini
    echo "\n${RED1}Super User powers needed to install required packages$WHITE"
    sudo apt install build-essential gedit xfce4-terminal w3m gcc
fi

if [ "$1" = '-cpp' ]; then
    if [ "$2" = '' ]; then
        echo "\nYou haven't write nothing!\nUsage: carrot -cpp <path>\n"
    else
        if [ ! -f $2 ]; then
            echo "\n${RED2}ERROR: This file doesn't exist!\n${RED1}Directory Example: /home/<username>/Documents/File.cpp\n$WHITE"
        else
            echo "\n${RED1}Compiling...$WHITE"
            g++ $2 -o carrotprogbash
            echo "${BLUE}Executing...$WHITE\n"
            if [ ! -f carrotprogbash ]; then
                echo "${RED2}ERROR: Compiled file not found. If you got this error after a compiling error, ignore this line.$WHITE\n"
            else
                ./carrotprogbash
                rm carrotprogbash
                echo "\n${GREEN}Executed!$WHITE\n"
            fi
        fi
    fi

elif [ "$1" = '-c' ]; then
    if [ "$2" = '' ]; then
        echo "\nYou haven't write nothing!\nUsage: carrot -c <path>\n"
    else
        if [ ! -f $2 ]; then
            echo "\n${RED2}ERROR: This file doesn't exist!\n${RED1}Directory Example: /home/<username>/Documents/File.c\n$WHITE"
        else
            echo "\n${RED1}Compiling...$WHITE"
            gcc $2 -o carrotprogbash
            echo "${BLUE}Executing...$WHITE\n"
            if [ ! -f carrotprogbash ]; then
                echo "${RED2}ERROR: Compiled file not found. If you got this error after a compiling error, ignore this line.$WHITE\n"
            else
                ./carrotprogbash
                rm carrotprogbash
                echo "\n${GREEN}Executed!$WHITE\n"
            fi
        fi
    fi

elif [ "$1" = '-deb' ]; then
    if [ "$2" = '' ]; then
        echo "\nYou haven't write the option!\nUsage: carrot -deb [-i/-r] <path>\n"
    elif [ "$2" = '-i' ]; then
        if [ "$3" = '' ]; then
            echo "\nYou haven't write the path!\nUsage: carrot -deb [-i/-r] <path>\n"
        else
            echo "\n${RED1}Super User powers needed to install packages$WHITE"
            sudo dpkg -i $3
        fi
    elif [ "$2" = '-r' ]; then
        if [ "$3" = '' ]; then
            echo "\nYou haven't write the path!\nUsage: carrot -deb [-i/-r] <path>\n"
        else
            echo "\n${RED1}Super User powers needed to install packages$WHITE"
            sudo dpkg -r $3
        fi
    else
        echo "\nInvalid option!\nUsage: carrot -deb [-i/-r] <path>\n"
    fi

elif [ "$1" = '-repeat' ]; then
    if [ "$2" = '' ]; then
        echo "\nYou haven't wrote nothing!\nUsage: carrot -repeat <string>\n"
    else
        echo "\n$2\n"
    fi

elif [ "$1" = '-carrotedit' ]; then
    echo "\n${RED2}WARNING! You are about to edit the Carrotshell program!$WHITE"
    echo -n "Are you still sure about editing it? [y/n] >> "
    read sas
    if [ "$sas" = 'y' ]; then
        echo "\n${RED1}Opening gedit...$WHITE"
        sudo gedit /usr/bin/carrot
    else
        echo "\n${GREEN}Aborted.$WHITE\n"
    fi

elif [ "$1" = '-remove' ]; then
    if [ "$2" = '' ]; then
        echo "\nYou haven't wrote nothing!\nUsage: carrot -remove <file path>\n${HEADER}Want to remove a directory (folder)?\nType 'carrot -remove ${RED1}-r${HEADER} <directory>'$WHITE\n"
    else
        rm $2 $3
    fi

elif [ "$1" = '-pi' ]; then
    if [ "$2" = '' ]; then
        echo "\nYou haven't wrote nothing!\nUsage: carrot -pi <package>\n"
    else
        echo "\n${RED1}Super User powers needed to install packages$WHITE"
        sudo apt install $2
    fi

elif [ "$1" = '-pr' ]; then
    if [ "$2" = '' ]; then
        echo "\nYou haven't wrote nothing!\nUsage: carrot -pr <package>\n"
    else
        echo "\n${RED1}Super User powers needed to remove packages$WHITE"
        sudo apt remove $2
    fi

elif [ "$1" = '-pu' ]; then
    echo "\n${RED1}Super User powers needed to update apt & upgrade packages$WHITE"
    sudo apt update && sudo apt upgrade

elif [ "$1" = '-update' ]; then
    if [ ! -d ~/.Carrotshell ]; then
        mkdir ~/.Carrotshell
        fi
    cd ~/.Carrotshell/
    wget https://raw.githubusercontent.com/SpheLC/Carrotshell/main/carrot
    echo "\n${RED1}Super User powers needed to update Carrotshell$WHITE"
    echo "${RED1}Press Enter if I ask you a question to confirm moving some files (~/.Carrotshell/carrot to /usr/bin/carrot)$WHITE"
    sudo mv ~/.Carrotshell/carrot /usr/bin
    sudo chmod +x /usr/bin/carrot
    echo "${UNDERLINE}${GREEN}Done!$WHITE"
    echo ""
    upd=1

elif [ "$1" = '-help' ]; then
    echo "$cu"
elif [ "$1" = '' ]; then
    echo "$cu"

elif [ "$1" = '-rustdir' ]; then
    if [ "$2" = '' ]; then
        echo "\n${RED2}You haven't wrote nothing!\n${RED1}Usage: carrot -rustdir <directory>\n(usually it is in ~/.cargo/bin)$WHITE\n"
    else
        if [ ! -d $2 ]; then
            echo "\n${RED2}ERROR: This directory doesn't exist!\n${RED1}Directory Example: /home/<username>/Documents\n$WHITE"
        else
            echo "\nWriting..."
            if [ ! -f ~/.Carrotshell/rust ]; then
                echo $2 >> ~/.Carrotshell/rust
            else
                rm ~/.Carrotshell/rust
                echo $2 >> ~/.Carrotshell/rust
            fi
            if [ ! -f $2/rustc ]; then
                echo "${RED2}Invalid directory! This directory that you wrote doesn't have the 'rustc' file inside!$WHITE\n"
            else
                echo "${GREEN}Done!$WHITE\n"
            fi
        fi
    fi

elif [ "$1" = '-rust' ]; then
    if [ "$2" = '' ]; then
        echo "\n${RED2}You haven't write nothing!\n${RED1}Usage: carrot -rust <path>\n"
    else
        if [ ! -f $2 ]; then
            echo "\n${RED2}ERROR: This file doesn't exist!\n${RED1}Directory Example: /home/<username>/Documents/File.rs\n$WHITE"
        else
            b=$(basename $2)
            c=${b%.*}
            if [ ! -f ~/.Carrotshell/rust ]; then
                echo "\n${RED2}ERROR: Rust Cargo directory it hasn't been set yet! Fix this by doing:\n${RED1}carrot -rustdir <path>$WHITE\n"
            else
                echo "\n${RED1}Compiling...$WHITE"
                $(cat ~/.Carrotshell/rust)/rustc $2
                echo "${BLUE}Executing...$WHITE\n"
                if [ ! -f $c ]; then
                    echo "\n${RED2}ERROR: Compiled file not found. If you got this error after a compiling error, ignore this line.$WHITE\n"
                else
                    ./$c
                    rm $c
                    echo "\n${GREEN}Executed!$WHITE\n"
                fi
            fi
        fi
    fi

#if command not found...
else
    echo "\n'$1' is an unexpected command"
    echo "$cu"
fi

#Check the version
veronline=$(w3m -dump https://raw.githubusercontent.com/SpheLC/Carrotshell/main/version_dontmindme)
if [ $veronline -gt $ver1 -a $upd -eq 0 ]; then
    echo "${RED2}   .$WHITE"
    echo "${RED2}  / \ $WHITE"
    echo "${RED2} / ${RED1}! ${RED2}\  ${BLUE}New version ${GREEN}avaiable${BLUE}! ${RED1}(V${veronline})$WHITE"
    echo "${RED2}+-----+\n\n${RED1}'carrot -update' to update!$WHITE\n"
elif [ $veronline -lt $ver1 ]; then
    echo "${RED1}ERROR: Your version is newer than the original release.\nTry to update Carrotshell to fix this error or just wait some minutes.\nYour version: $ver1 | Current version: $veronline$WHITE\n"
fi

#Carrotshell By Sphe
